jobs:
- job: Windows_VS2017
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - template: Scripts/azure_pipelines_build_windows_vs2017.yml
- job: Windows_VS2019
  pool:
    vmImage: 'windows-2019'
  steps:
  - template: Scripts/azure_pipelines_build_windows_vs2019.yml
- job: Linux
  pool:
    vmImage: 'Ubuntu-16.04'
  steps:
  - template: Scripts/azure_pipelines_build_linux.yml
- job: macOS
  pool:
    vmImage: 'macOS-10.14'
  steps:
  - template: Scripts/azure_pipelines_build_macos.yml